### ISSUE TITLE
Q: Is this okay to install?

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/outline_ynh#25]
I can't tell from the readme if this is in a place to install. I'd be happy to test things out if so!

**Comment by Limezy** [comment]
Hi, are you a Yunohost user ?

If not you can check out the Yunohost project here :
https://yunohost.org/en/whatsyunohost?q=%2Fwhatsyunohost
Idea is to have a "one-click" install for a full self-hosted setup (either on a VPS or on your old computer at home)
https://yunohost.org/en/install

The Yunohost contributors created a lot of "Yunohost apps", which are a bunch of easily used scripts to install, backup, upgrade popular open source and self-hostable softwares, such as Nextcloud, Mastodon, Peertube, Wallabag, Rainloop, Wordpress, Grav and so much more (you can see the app catalog here : https://yunohost.org/en/apps)

Before releasing an app, there is a obviously a lot of heavy testing and validation involved since Yunohost aims at helping non professional people to selfhost. Every app has to install smoothly in one clic and nothing should be broken or no data should be lost !

I have recently started building a Yunohost app for Outline and here is the repository for it.
It is currently working quite well, with all features being enabled (Slack auth, https, minio for pictures, email server etc...).
However it didn't go yet through all the testing process so it's not yet officially part of the Yunohost app catalog.

Should you want to test Yunohost and that future Yunohost app, I would be glad to have your feedback ! However, please don't install it on a prod server, and please don't upload yet any critical data on it.
I'll update the Readme in a few hours so that you'll have the basic steps about how to install Outline on Yunohost.

I also warn you that installing Outline through Yunohost is not (and will probably never be) an officially supported install method.

Should you just want to install and / or test Outline, then the real repository is here : https://github.com/outline/outline

**Comment by brimwats** [comment]
Oh jeeze, sorry, I should have said I'm already a pretty hardcore YNH user. I went ahead and installed it before you replied here and I got stuck on the Slack steps. I got the client secret and all of that, but I think the hangup is in "saving" the new slack app. slack wants me to add a permission or something before I can save it but I don't know what to add for that aspect. 

So right now when I try to "Login via Slack" I get:

`redirect_uri did not match any configured URIs. Passed URI: https://outline.DOMAIN.TLD/auth/slack.callback `

**Comment by Limezy** [comment]
Oh great if you are a Ynh user already ! 

Which version did you install ? 0.60.1-alpha ?

Yeah the missing step is to add an url into your slack app Auth

**Comment by brimwats** [comment]
I just added it via the github URL—I didn't see the note about not installing it on a production server 🙈

well, it installs without issue, and I got all that set up. So I can test adding the URL into the slack app auth if you tell me what section it goes in!

**Comment by Limezy** [comment]
You should go to that page OAuth & Permissions

![image](https://user-images.githubusercontent.com/24638389/142093357-1315b2bb-0aa0-4125-a1a4-4dd8a7c63bc4.png)

And then add a redirect URI (should be the exact one as what you had in your error)

![image](https://user-images.githubusercontent.com/24638389/142093471-b36a8503-d6f9-4f28-8476-6418fcc87a67.png)

**Comment by brimwats** [comment]
I found it! It works! yay!

**Comment by brimwats** [comment]
you can close this issue if you want! I will try to break things and add any new issues

**Comment by Limezy** [comment]
You are very close to have a working install ! But please make sure to use the latest one as per my forum post

**Comment by Limezy** [comment]
> I just added it via the github URL—I didn't see the note about not installing it on a production server 🙈
> 
> 
> 
> well, it installs without issue, and I got all that set up. So I can test adding the URL into the slack app auth if you tell me what section it goes in!

Let me be honest with you, it's already running without any issue on my prod server since a few days 😆 
If you are ok with the risk, fine, but I just don't want to be seen as responsible - especially knowing that this is my first app and I'm still a pretty beginner packager !

If you didn't install the latest one, I suggest you remove it and install it again instead of upgrading. Upgrade wasn't working well on previous versions.

**Comment by brimwats** [comment]
okay! sorry I missed the forum post. how do I make sure I install the latest one? is it a specific URL or branch?

**Comment by Limezy** [comment]
Please use that URL for installation : https://github.com/YunoHost-Apps/outline_ynh/tree/v0.60.1-alpha

Forum post is here : https://forum.yunohost.org/t/outline-wiki-an-open-extensible-wiki-for-your-team-built-using-react-and-node-js/17197/2

Are you a packager ? If yes I would be glad to get some help to have the Continuous Integration working 😀

**Comment by Limezy** [comment]
> Please use that URL for installation : https://github.com/YunoHost-Apps/outline_ynh/tree/v0.60.1-alpha
> 
> Forum post is here : [https://forum.yunohost.org/t/outline-wiki-an-open-extensible-wiki-for-your-team-built-using-react-and-node/17197/2](https://forum.yunohost.org/t/outline-wiki-an-open-extensible-wiki-for-your-team-built-using-react-and-node-js/17197/2)
> 
> Are you a packager ? If yes I would be glad to get some help to have the Continuous Integration working 😀

In fact I have merged that v0.60.1-alpha branch into master already.
So if you used https://github.com/YunoHost-Apps/outline_ynh url today you are up to date, no need for any change !
