### ISSUE TITLE
Feature: Custom OIDC Server configuration set of files. 

### ISSUE THREAD

**Issue by CtheCondor** [YunoHost-Apps/outline_ynh#91]
### Describe the ~~bug~~ feature

Can an alternative .env/config file be provided that can be used to use a custom OIDC providers.

NA ~Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*~
NA~YunoHost version: x.x.x~
- I have access to my server: Yes
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to ~~reproduce~~ proceed
1.  Modify the following fields in the `.env` file
```
OIDC_CLIENT_ID=__OIDC_NAME__
OIDC_CLIENT_SECRET=__OIDC_SECRET__
OIDC_AUTH_URI=__DEX_AUTH_URI__
OIDC_TOKEN_URI=__DEX_TOKEN_URI__
OIDC_USERINFO_URI=__DEX_USER_URI__
```
2. Modify the section in `scripts/install` following:
```
#=================================================
# INSTALL DEX APP FOR OAUTH2 / OIDC
#=================================================
```
essentially removing/revising every variable with dex in it at least.
3. Modify the backup/remove files
4. Some other files?

**Comment by Limezy** [comment]
Hi !
Is this a thing about : 
* Using a "custom" OIDC provider that isn't Dex for your personal use ?
* You believe that this Yunohost app should propose by default different OIDC providers, to be chosen at installation time ?

In case it's personal, it's easy : install as normal, modify your .env in /var/www/outline/.env, uninstall Dex. You could create a fork of that repo with a modification of scripts/upgrade so that it doesn't touch the .env file and you should be good

In case it's about proposing different OIDC providers, may I know why ?

**Comment by CtheCondor** [comment]
How do I direct the Outline instance to use the modified .env or is that done by default when the service is restarted?
This is 90% personal but also the ability to use OIDC in more than one instance rather than traditional Yunohost LDAP might be an option other's may like as services.

**Comment by Limezy** [comment]
Yep, done by default when you restart the service. You will have to do some PostgreSQL modifications on the users table if you want to keep your old users with the new OIDC. You will probably need to replace that .env by hand every time you upgrade the outline app. Should work not too bad ! (But please backup !)

**Comment by Limezy** [comment]
I'll close as not planned for now as my time is very limited.
Feel free to open a PR though
